export type Spec = { label: string; value: string }
export type Highlight = { icon: string; label: string; value: string }

export type Product = {
  slug: string
  category: string
  nameEn: string
  nameSi: string
  price: number | null
  priceRegular?: number | null
  descEn: string
  descSi: string
  isFlagship?: boolean
  image?: string
  highlights?: Highlight[]
  specs?: Spec[]
  features?: string[]
  applications?: string[]
  warranty?: string
  includes?: string[]
}

export type Category = {
  slug: string
  nameEn: string
  nameSi: string
  icon: string
  hidden?: boolean
}

export const CATEGORIES: Category[] = [
  { slug: 'liquid-machine',  nameEn: 'Liquid Machine',        nameSi: 'ද්‍රව යන්ත්‍ර',              icon: '💧' },
  { slug: 'roaster-machine', nameEn: 'Roaster Machine',       nameSi: 'රෝස්ටර් යන්ත්‍රය',           icon: '🔥' },
  { slug: 'kottu-machine',   nameEn: 'Kottu Cutting Machine', nameSi: 'කොත්තු කපන යන්ත්‍රය',       icon: '🍽️' },
  { slug: 'dehydrators',     nameEn: 'Dehydrate Machines',    nameSi: 'විජලනය යන්ත්‍ර',           icon: '🌡️' },
  { slug: 'grinding-mills',  nameEn: 'Grinding Mills',        nameSi: 'ඇඹරීම් යන්ත්‍ර',          icon: '⚙️' },
  { slug: 'band-sealers',    nameEn: 'Band Sealers',          nameSi: 'සීල් යන්ත්‍ර',             icon: '🔒' },
  { slug: 'vacuum-sealers',  nameEn: 'Vacuum Sealers',        nameSi: 'වැකුම් සීල් යන්ත්‍ර',     icon: '🌀' },
  { slug: 'rice-mills',      nameEn: 'Rice Mills',            nameSi: 'සහල් යන්ත්‍ර',             icon: '🌾' },
  { slug: 'slicers',         nameEn: 'Slicer Machines',       nameSi: 'කැබලි කපන යන්ත්‍ර',       icon: '🔪' },
  { slug: 'chuff-cutters',   nameEn: 'Chuff Cutters',         nameSi: 'චෆ් කටර්ස් යන්ත්‍ර',      icon: '🌿' },
  { slug: 'wood-chippers',   nameEn: 'Wood Chippers',         nameSi: 'ලී කොටන යන්ත්‍ර',         icon: '🌲' },
  { slug: 'feed-pellet',     nameEn: 'Feed Pellet Machines',  nameSi: 'ගොරෝසු ඇට යන්ත්‍ර',      icon: '🐄' },
  { slug: 'budget-packs',    nameEn: 'Budget Packs',          nameSi: 'ලාභදායී පැකේජ',            icon: '📦', hidden: true },
]

// Shared dehydrator features/applications applied to all dehydrator models
const DEHYDRATOR_FEATURES = [
  'Adjustable temperature control (35°C–75°C)',
  'Precise timer control',
  'Built-in interior light for monitoring',
  'Uniform air circulation for even drying',
  'Energy efficient — low power consumption',
  'Preserves original taste and nutritional value',
  'Stainless steel food-grade trays',
  'Suitable for home and commercial use',
]

const DEHYDRATOR_APPLICATIONS = [
  'Fruits & vegetables (mango, banana, tomato)',
  'Tea & herbal leaves',
  'Mushrooms & fungi',
  'Seafood (fish, prawns)',
  'Meat jerky',
  'Spices & herbs',
  'Fruit rolls',
  'Grains & seeds',
]

const DEHYDRATOR_INCLUDES = [
  'Drying Trays (quantity per model)',
  'Temperature Controller',
  'Timer',
  'Manual',
]

export const PRODUCTS: Product[] = [
  // ── Liquid / Filling & Packing ──
  {
    slug: 'automatic-liquid-filling-packing-machine',
    category: 'liquid-machine',
    nameEn: 'Automatic Liquid Filling & Packing Machine',
    nameSi: 'ස්වයංක්‍රීය ද්‍රව පිරවීම සහ ඇසුරුම් කිරීමේ යන්ත්‍රය',
    price: 460000,
    priceRegular: 575000,
    descEn: 'Food-grade stainless steel. Fills 3–200ml. Speed 10–18 bags/min. Includes 4-line date coder and eye mark sensor.',
    descSi: 'අයිස් පොප්, ජූස්, පොල්තෙල්, සිරි වර්ග අතුළ ඔබේ නිෂ්පාදනය ස්වයංක්‍රීයව ඇසුරුම් කරන යන්ත්‍රය',
    isFlagship: true,
    image: '/images/products/automatic-liquid-filling-packing-machine.png',
  },
  {
    slug: 'y-200s-liquid-packing-machine',
    category: 'liquid-machine',
    nameEn: 'Y-200S 18cm Electric Liquid Packing Machine Three Side',
    nameSi: 'Y-200S ත්‍රිකෝණ ද්‍රව ඇසුරුම් යන්ත්‍රය',
    price: 435000,
    descEn: '18cm three-side sealing electric liquid packing machine.',
    descSi: 'ත්‍රිකෝණ ඇසුරුමෙන් ද්‍රව ඇසුරුම් කරන යන්ත්‍රය.',
    image: '/images/products/y-200s-liquid-packing-machine.png',
  },
  {
    slug: '999g-filling-packing-machine',
    category: 'liquid-machine',
    nameEn: '999g Large Packing Full Set (3-Machine)',
    nameSi: '999g විශාල ඇසුරුම් යන්ත්‍ර සම්පූර්ණ කට්ටලය',
    price: 1495000,
    descEn: 'Complete 3-machine liquid filling and packing set for large-scale packaging up to 999g.',
    descSi: 'විශාල ඇසුරුම් සඳහා සම්පූර්ණ ත්‍රි-යන්ත්‍ර ද්‍රව ඇසුරුම් කට්ටලය.',
    image: '/images/products/999g-filling-packing.png',
    highlights: [
      { icon: '📦', label: 'Pack Size', value: '10–21 cm' },
      { icon: '🏭', label: 'Scale', value: 'Large Commercial' },
      { icon: '🔧', label: 'Machines', value: '3-Machine Set' },
    ],
    features: [
      'Complete 3-machine integrated system',
      'Handles packet sizes from 10 cm to 21 cm',
      'Suitable for large-scale commercial operations',
      'Free island-wide delivery and installation',
    ],
    warranty: '12-Month Warranty',
  },
  // ── Roaster Machine ──
  {
    slug: 'sy25a-roaster',
    category: 'roaster-machine',
    nameEn: 'SY 25A Roaster 304 SS Inner Body Electric',
    nameSi: 'SY 25A රෝස්ටර් 304 SS අභ්‍යන්තර ශරීරය',
    price: 595000,
    descEn: '304 stainless steel drum roaster. 10–35 kg/h capacity, 4 kW electric heating with uniform temperature distribution.',
    descSi: '304 SS රෝස්ටර් — කෝපි, ධාන්‍ය, කුළු බඩු, ඇට වර්ග ඒකාකාරව රෝස්ට් කිරීමේ යන්ත්‍රය.',
    isFlagship: true,
    image: '/images/products/sy25a-roaster.jpeg',
    highlights: [
      { icon: '🔥', label: 'Capacity',   value: '10–35 kg/h' },
      { icon: '⚡', label: 'Power',      value: '4 kW Electric' },
      { icon: '⚖️', label: 'Weight',     value: '80 kg' },
    ],
    specs: [
      { label: 'Power',            value: '4 kW Electric' },
      { label: 'Output Capacity',  value: '10–35 kg/hour' },
      { label: 'Machine Weight',   value: '80 kg' },
      { label: 'Machine Size',     value: '110 × 50 × 95 cm' },
      { label: 'Inner Material',   value: '304 Stainless Steel' },
      { label: 'Warranty',         value: '12 months' },
    ],
    features: [
      'Rotating drum ensures uniform heat distribution',
      '304 stainless steel interior — food-safe & durable',
      'Efficient 4 kW electric heating for rapid roasting',
      'Processes 10–35 kg/h for commercial operations',
      'Adjustable temperature control',
      'Free operator training at Dambulla showroom',
    ],
    applications: [
      'Coffee beans',
      'Seeds & grains',
      'Spices (pepper, coriander)',
      'Nuts & cashews',
      'Cocoa beans',
    ],
    warranty: '12-Month Warranty',
    includes: [
      'SY 25A Roaster Unit',
      'Free island-wide delivery',
      'Free installation & training',
      'Legal agreement',
    ],
  },
  // ── Kottu Cutting Machine ──
  {
    slug: 'kottu-cutting-machine',
    category: 'kottu-machine',
    nameEn: 'Commercial Kottu Cutting Machine',
    nameSi: 'වාණිජ කොත්තු කපන යන්ත්‍රය',
    price: 99500,
    priceRegular: 124375,
    descEn: 'SS304 stainless steel commercial kottu cutter. 150 kg/h capacity, 1.5 HP motor. Made in Sri Lanka.',
    descSi: 'SS304 ස්ටීල් කොත්තු කපන යන්ත්‍රය — හෝටල්, කෑම් සාප්පු, කේටරින් සඳහා.',
    isFlagship: true,
    image: '/images/products/kottu-cutting-machine.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '150 kg/h' },
      { icon: '💪', label: 'Power',    value: '1.5 HP / 1500W' },
      { icon: '🇱🇰', label: 'Origin',  value: 'Made in Sri Lanka' },
    ],
    specs: [
      { label: 'Power',     value: '1.5 HP (1500W)' },
      { label: 'Capacity',  value: '150 kg/hour' },
      { label: 'Material',  value: 'SS304 Stainless Steel' },
      { label: 'Warranty',  value: '1 Year (Parts & Service)' },
      { label: 'Origin',    value: 'Made in Sri Lanka' },
    ],
    features: [
      'Rapid slicing for kottu, fried rice and noodles',
      'Cuts meat, cheese, and vegetables uniformly',
      'Single operator needed',
      'SS304 commercial-grade stainless steel',
      'Free island-wide delivery and installation',
    ],
    applications: [
      'Hotels & restaurants',
      'Kottu shops',
      'Catering services',
      'Food courts',
    ],
    warranty: '1-Year Warranty (Parts & Service)',
  },
  // ── Dehydrators ──
  {
    slug: '8-tray-dryer',
    category: 'dehydrators',
    nameEn: '8-Tray Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 8ක් ඇති ආහාර සූකාරය',
    price: 89500,
    descEn: '8 tray food dehydrator.',
    descSi: 'ට්‍රේ 8ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/8-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '8 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '10f-tray-dryer',
    category: 'dehydrators',
    nameEn: '10F-Trays Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 10ක් ඇති ආහාර සූකාරය',
    price: 95000,
    descEn: '10 tray food dehydrator.',
    descSi: 'ට්‍රේ 10ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/10f-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '10 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '16a-tray-dryer',
    category: 'dehydrators',
    nameEn: '16A-Trays Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 16ක් ඇති ආහාර සූකාරය',
    price: 195000,
    descEn: '16 tray food dehydrator.',
    descSi: 'ට්‍රේ 16ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/16a-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '16 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '18b-tray-dryer',
    category: 'dehydrators',
    nameEn: '18B-Trays Food and Vegetable Dryer',
    nameSi: 'ට්‍රේ 18ක් ඇති ආහාර සූකාරය',
    price: 125000,
    descEn: '18 tray food dehydrator.',
    descSi: 'ට්‍රේ 18ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/18b-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '18 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '20j-tray-dryer',
    category: 'dehydrators',
    nameEn: '20J-Tray Fruit and Vegetable Dryer Manual',
    nameSi: 'ට්‍රේ 20ක් ඇති ශ්‍රිත සූකාරය',
    price: 225000,
    descEn: '20 tray manual food dehydrator.',
    descSi: 'ශ්‍රිත ආහාර සූකාරය.',
    image: '/images/products/20j-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '20 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '24-tray-dryer',
    category: 'dehydrators',
    nameEn: '24-Trays Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 24ක් ඇති ආහාර සූකාරය',
    price: 245000,
    descEn: '24 tray food dehydrator.',
    descSi: 'ට්‍රේ 24ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/24-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '24 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '24j-tray-dryer',
    category: 'dehydrators',
    nameEn: '24J-Trays Food and Vegetable Dryer',
    nameSi: 'ට්‍රේ 24J ආහාර සූකාරය',
    price: 245000,
    descEn: '24J tray food dehydrator.',
    descSi: 'ට්‍රේ 24J ආහාර සූකාරය.',
    image: '/images/products/24j-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '24 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '32-tray-dryer',
    category: 'dehydrators',
    nameEn: '32-Tray Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 32ක් ඇති ආහාර සූකාරය',
    price: 445000,
    descEn: '32 tray food dehydrator.',
    descSi: 'ට්‍රේ 32ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/32-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '32 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '32j-tray-dryer',
    category: 'dehydrators',
    nameEn: '32J-Trays Food and Vegetable Dryer',
    nameSi: 'ට්‍රේ 32J ආහාර සූකාරය',
    price: 445000,
    descEn: '32J tray food dehydrator.',
    descSi: 'ට්‍රේ 32J ආහාර සූකාරය.',
    image: '/images/products/32j-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '32 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '40-tray-dryer',
    category: 'dehydrators',
    nameEn: '40-Trays Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 40ක් ඇති ආහාර සූකාරය',
    price: 445000,
    descEn: '40 tray food dehydrator.',
    descSi: 'ට්‍රේ 40ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/40-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '40 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '48-tray-dryer',
    category: 'dehydrators',
    nameEn: '48-Trays Food and Vegetable Dryer',
    nameSi: 'ට්‍රේ 48ක් ඇති ආහාර සූකාරය',
    price: 495000,
    descEn: '48 tray food dehydrator.',
    descSi: 'ට්‍රේ 48ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/48-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '48 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '80-tray-dryer',
    category: 'dehydrators',
    nameEn: '80-Trays Fruit and Vegetable Dryer',
    nameSi: 'ට්‍රේ 80ක් ඇති ආහාර සූකාරය',
    price: 795000,
    descEn: '80 tray food dehydrator.',
    descSi: 'ට්‍රේ 80ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/80-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '80 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  {
    slug: '96-tray-dryer',
    category: 'dehydrators',
    nameEn: '96-Trays Food and Vegetable Dryer',
    nameSi: 'ට්‍රේ 96ක් ඇති ආහාර සූකාරය',
    price: 895000,
    descEn: '96 tray food dehydrator.',
    descSi: 'ට්‍රේ 96ක් ඇති ආහාර සූකාරය.',
    image: '/images/products/96-tray-dryer.png',
    highlights: [
      { icon: '🌡️', label: 'Trays', value: '96 Trays' },
      { icon: '🌡️', label: 'Temp Range', value: '35–75°C' },
      { icon: '⚡', label: 'Power', value: 'Energy Saving' },
    ],
    features: DEHYDRATOR_FEATURES,
    applications: DEHYDRATOR_APPLICATIONS,
    warranty: '12-Month Warranty',
    includes: DEHYDRATOR_INCLUDES,
  },
  // ── Grinding Mills ──
  {
    slug: '9fc-grinding-mill',
    category: 'grinding-mills',
    nameEn: '9FC 2021 ONE SHOT Grinding Mill',
    nameSi: '9FC ඇඹරීම් යන්ත්‍රය',
    price: 169000,
    descEn: 'Heavy-duty grinding mill.',
    descSi: 'ශක්තිමත් ඇඹරීම් යන්ත්‍රය.',
    image: '/images/products/9fc-grinding-mill.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '20–70 kg/h' },
      { icon: '💪', label: 'Power', value: '3HP / 220V' },
      { icon: '🎯', label: 'Fineness', value: '0.2–5 mm' },
    ],
    specs: [
      { label: 'Capacity', value: '20–70 kg/h' },
      { label: 'Power', value: '3HP / 220V Single Phase' },
      { label: 'Motor RPM', value: '2800 RPM' },
      { label: 'Fineness', value: '0.2–5 mm' },
      { label: 'Material', value: 'Food-grade stainless steel' },
      { label: 'Dimensions', value: '61 × 45 × 76 cm' },
      { label: 'Net Weight', value: '48.7 kg' },
      { label: 'Warranty', value: '12 months machine / 6 months motor' },
    ],
    features: [
      '5 interchangeable sieve types included',
      'Food-grade stainless steel hopper and body',
      'Smooth vibration-free operation',
      '100% copper-plated 3HP domestic motor',
      'Safety belt cover protection',
      'Compact and easy to clean',
      'Low power consumption',
    ],
    applications: [
      'Chili powder & chili flakes',
      'Rice flour & wet rice flour',
      'Cinnamon powder',
      'Sugarcane & grain crushing',
      'Multi-spice grinding',
      'Mung bean grinding',
    ],
    warranty: '12-Month Machine Warranty',
    includes: [
      '9FC Grinding Mill Unit',
      '5 Interchangeable Sieves',
      'Safety Belt Cover',
    ],
  },
  {
    slug: 'ss-grinding-mill',
    category: 'grinding-mills',
    nameEn: 'BB-F2023S Fully SS Grinding Mill',
    nameSi: 'සම්පූර්ණ SS ඇඹරීම් යන්ත්‍රය',
    price: 259000,
    descEn: 'Full SS304 stainless steel mill. 80–150 kg/h, 3HP, 5 interchangeable grinding nets.',
    descSi: 'සම්පූර්ණ ස්ටීල් SS304 ඇඹරීම් යන්ත්‍රය.',
    image: '/images/products/ss-grinding-mill.jpg',
  },
  {
    slug: 'ultrafine-mill',
    category: 'grinding-mills',
    nameEn: 'Ultrafine Grinding Mill',
    nameSi: 'අති සූක්ෂ්ම ඇඹරීම් යන්ත්‍රය',
    price: 235000,
    descEn: 'Ultrafine powder grinding.',
    descSi: 'අති සූක්ෂ්ම කුඩු ඇඹරීම.',
    image: '/images/products/ultrafine-mill.png',
    highlights: [
      { icon: '🎯', label: 'Fineness', value: '0.02–3 mm' },
      { icon: '💪', label: 'Power', value: '3HP Motor' },
      { icon: '📦', label: 'Capacity', value: '25–80 kg' },
    ],
    specs: [
      { label: 'Grinding Capacity', value: '25–80 kg' },
      { label: 'Fineness', value: '0.02–3 mm' },
      { label: 'Motor', value: '3HP / 100% Copper Plated' },
      { label: 'Material', value: 'Stainless Steel Chamber (Food-safe)' },
      { label: 'Included Nets', value: '3 different mesh nets' },
      { label: 'Warranty', value: '12 months' },
    ],
    features: [
      'Stainless steel chamber — food-safe & hygienic',
      'Ultra-fine 0.02mm powder capability',
      '3 interchangeable mesh nets included',
      'Smooth vibration-free operation',
      'Compact & easy to clean',
      'Low power consumption',
      'Strong white iron teeth construction',
    ],
    applications: [
      'Rice flour',
      'Turmeric powder',
      'Cinnamon powder',
      'Pepper grinding',
      'Coffee grinding',
      'Herb processing',
      'Spice powders',
    ],
    warranty: '12-Month Warranty',
    includes: [
      'Ultrafine Grinding Mill Unit',
      '3 Mesh Nets',
      'Safety Belt Cover',
      'Plastic Exit Window',
    ],
  },
  {
    slug: '24k-disk-mill',
    category: 'grinding-mills',
    nameEn: '24K Disk Grinding Mill',
    nameSi: '24K ඩිස්ක් ඇඹරීම් යන්ත්‍රය',
    price: null,
    descEn: 'Disk type grinding mill.',
    descSi: 'ඩිස්ක් ඇඹරීම් යන්ත්‍රය.',
    image: '/images/products/24k-disk-mill.jpg',
  },
  {
    slug: 'km20-grinder-half-ss',
    category: 'grinding-mills',
    nameEn: 'KM20 Multi Spice Grinder SS Half Body',
    nameSi: 'KM20 බහු-කුළු ඇඹරීම් (අර්ධ SS)',
    price: 169000,
    descEn: 'Multi-spice grinder, SS half body.',
    descSi: 'KM20 ඇඹරීම් යන්ත්‍රය.',
    image: '/images/products/km20-grinder-half-ss.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '30–80 kg/h' },
      { icon: '🔌', label: 'Voltage', value: '220V' },
      { icon: '⚖️', label: 'Weight', value: '55 kg' },
    ],
    specs: [
      { label: 'Voltage', value: '220V' },
      { label: 'Capacity', value: '30–80 kg/h' },
      { label: 'Dimensions', value: '31 × 30 × 48 cm' },
      { label: 'Weight', value: '55 kg' },
      { label: 'Material', value: 'Stainless Steel Half Body' },
      { label: 'Industry', value: 'Food Processing' },
      { label: 'Warranty', value: '6 months' },
    ],
    features: [
      'SS half-body for hygiene and durability',
      'High-volume industrial grinding',
      'Engineered for commercial food processing',
      'Multi-spice grinding capability',
      'Efficient motor system',
    ],
    applications: [
      'Rice grinding',
      'Grain processing',
      'Spice grinding',
      'Commercial food manufacturing',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'km20-grinder-full-ss',
    category: 'grinding-mills',
    nameEn: 'KM20 Multi Spice Grinder SS Full Body',
    nameSi: 'KM20 බහු-කුළු ඇඹරීම් (සම්පූර්ණ SS)',
    price: 245000,
    descEn: 'Multi-spice grinder, full SS body.',
    descSi: 'KM20 සම්පූර්ණ SS ඇඹරීම් යන්ත්‍රය.',
    image: '/images/products/km20-grinder-full-ss.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '30–80 kg/h' },
      { icon: '🔌', label: 'Voltage', value: '220V' },
      { icon: '⚖️', label: 'Weight', value: '60 kg' },
    ],
    specs: [
      { label: 'Voltage', value: '220V' },
      { label: 'Weight', value: '60 kg' },
      { label: 'Dimensions', value: '63 × 35 × 96 cm' },
      { label: 'Material', value: 'Full Stainless Steel Body' },
      { label: 'Warranty', value: '6 months' },
    ],
    features: [
      'Full stainless steel body — maximum hygiene',
      'Heavy-duty commercial grade construction',
      'Multi-spice grinding capability',
      'Industrial-grade performance',
      'Durable and corrosion-resistant',
    ],
    applications: [
      'Rice grinding',
      'Grain processing',
      'Spice grinding',
      'Commercial food manufacturing',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'km20-grinder-cyclone-1ph',
    category: 'grinding-mills',
    nameEn: 'KM20 Grinder with Cyclone Single Phase',
    nameSi: 'KM20 Cyclone ඇඹරීම් (1 Phase)',
    price: 175000,
    descEn: 'KM20 with cyclone dust collection, single phase motor.',
    descSi: 'KM20 Cyclone ඇඹරීම් (1 Phase).',
    image: '/images/products/km20-grinder-cyclone-1ph.png',
    highlights: [
      { icon: '💪', label: 'Power', value: '4HP / 380V' },
      { icon: '⚡', label: 'Capacity', value: '30–80 kg/h' },
      { icon: '🔄', label: 'System', value: 'Cyclone' },
    ],
    specs: [
      { label: 'Voltage', value: '380V (3-Phase)' },
      { label: 'Power', value: '4HP / 2.2kW' },
      { label: 'Capacity', value: '30–80 kg/h' },
      { label: 'Dimensions', value: '78 × 76 × 122 cm' },
      { label: 'Warranty', value: '6 months' },
    ],
    features: [
      'Cyclone dust collection system',
      '3-phase high-power motor',
      'High-volume industrial operation',
      'Reduced dust emission',
      'Suitable for large-scale production',
    ],
    applications: [
      'Large-scale spice grinding',
      'Commercial rice flour',
      'Industrial food processing',
      'High-volume grain milling',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'km20s-grinder',
    category: 'grinding-mills',
    nameEn: 'KM20S Multi Spice Grinder',
    nameSi: 'KM20S බහු-කුළු ඇඹරීම් යන්ත්‍රය',
    price: 125000,
    descEn: 'KM20S compact multi-spice grinder.',
    descSi: 'KM20S ඇඹරීම් යන්ත්‍රය.',
    image: '/images/products/km20s-grinder.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '30–80 kg/h' },
      { icon: '🔌', label: 'Voltage',  value: '220V' },
      { icon: '⚙️', label: 'Type',     value: 'Multi-Spice' },
    ],
    features: [
      'Compact multi-spice grinding capability',
      'Stainless steel body for hygiene',
      'High-volume commercial grinding',
      'Easy to clean and maintain',
    ],
    applications: [
      'Spice grinding',
      'Rice flour',
      'Commercial food processing',
    ],
    warranty: '6-Month Warranty',
  },
  // ── Band Sealers ──
  {
    slug: 'fr-545-band-sealer',
    category: 'band-sealers',
    nameEn: 'FR-545 Band Sealer',
    nameSi: 'FR-545 බෑන්ඩ් සීල්',
    price: 59500,
    descEn: 'Continuous band sealer.',
    descSi: 'FR-545 බෑන්ඩ් සීල් යන්ත්‍රය.',
    image: '/images/products/fr-545-band-sealer.png',
    highlights: [
      { icon: '🔒', label: 'Type', value: 'Continuous Band' },
      { icon: '⚡', label: 'Width', value: '450 mm' },
      { icon: '🔄', label: 'Speed', value: 'Adjustable' },
    ],
    specs: [
      { label: 'Model', value: 'FR-545' },
      { label: 'Sealing Width', value: '450 mm' },
      { label: 'Material', value: 'Stainless Steel' },
      { label: 'Operation', value: 'Continuous Band Sealing' },
    ],
    features: [
      'Continuous band sealing for high speed production',
      'Suitable for bags pouches and flexible packaging',
      'Adjustable sealing speed and temperature',
      'Ink ribbon date coding option',
      'Compact footprint for small spaces',
    ],
    applications: [
      'Rice bags',
      'Spice pouches',
      'Snack packaging',
      'Flour bags',
      'General food packaging',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'fr-770-band-sealer',
    category: 'band-sealers',
    nameEn: 'FR-770 Band Sealer',
    nameSi: 'FR-770 බෑන්ඩ් සීල්',
    price: 149500,
    descEn: 'Continuous band sealer.',
    descSi: 'FR-770 බෑන්ඩ් සීල් යන්ත්‍රය.',
    image: '/images/products/fr-770-band-sealer.png',
    highlights: [
      { icon: '🔒', label: 'Type', value: 'Continuous Band' },
      { icon: '⚡', label: 'Width', value: '770 mm' },
      { icon: '🔄', label: 'Speed', value: 'Adjustable' },
    ],
    specs: [
      { label: 'Model', value: 'FR-770' },
      { label: 'Sealing Width', value: '770 mm' },
      { label: 'Material', value: 'Stainless Steel' },
      { label: 'Operation', value: 'Continuous Band Sealing' },
    ],
    features: [
      'Wider 770mm sealing for larger bags',
      'Continuous band sealing system',
      'Adjustable speed and temperature',
      'Date coding capable',
      'Commercial-grade construction',
    ],
    applications: [
      'Large bag packaging',
      'Commercial rice/flour bags',
      'Industrial food packaging',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'dbf-1000-sealer',
    category: 'band-sealers',
    nameEn: 'DBF-1000 Sealer',
    nameSi: 'DBF-1000 සීල්',
    price: null,
    descEn: 'Heavy-duty band sealer.',
    descSi: 'DBF-1000 සීල් යන්ත්‍රය.',
    image: '/images/products/dbf-1000-sealer.png',
    highlights: [
      { icon: '🔒', label: 'Type', value: 'Heavy Duty' },
      { icon: '⚡', label: 'Width', value: '1000 mm' },
      { icon: '💪', label: 'Duty', value: 'Heavy Duty' },
    ],
    features: [
      'Heavy-duty 1000mm wide sealing',
      'High-speed continuous operation',
      'Commercial and industrial grade',
      'Suitable for large volume packaging',
    ],
    applications: [
      'Industrial food packaging',
      'Large bag sealing',
      'Commercial distribution packaging',
    ],
    warranty: '6-Month Warranty',
  },
  // ── Vacuum Sealers ──
  {
    slug: 'dz400-2r',
    category: 'vacuum-sealers',
    nameEn: 'DZ400-2R Vacuum Sealer',
    nameSi: 'DZ400-2R රික්ත සීල්',
    price: 595000,
    descEn: 'Round-chamber vacuum sealer 400mm.',
    descSi: 'DZ400-2R රික්ත සීල් යන්ත්‍රය.',
    image: '/images/products/dz400-2r.png',
    highlights: [
      { icon: '🌀', label: 'Type', value: 'Round Chamber' },
      { icon: '🛡', label: 'Body', value: 'SS Body' },
      { icon: '🔄', label: 'Operation', value: 'Automatic' },
    ],
    features: [
      'Round chamber vacuum sealing',
      'Hygienic stainless steel body',
      'Automatic vacuum and sealing cycle',
      'Extends product freshness significantly',
    ],
    applications: ['Fresh meat & fish', 'Cooked food', 'Grains', 'Commercial packaging'],
    warranty: '1-Year Warranty',
  },
  {
    slug: 'dz400-2d',
    category: 'vacuum-sealers',
    nameEn: 'DZ400-2D Vacuum Sealer',
    nameSi: 'DZ400-2D රික්ත සීල්',
    price: null,
    descEn: 'Double-chamber vacuum sealer.',
    descSi: 'DZ400-2D රික්ත සීල් යන්ත්‍රය.',
    image: '/images/products/dz400-2d.png',
    highlights: [
      { icon: '🌀', label: 'Type', value: 'Double Chamber' },
      { icon: '🛡', label: 'Body', value: 'SS Body' },
      { icon: '🔄', label: 'Operation', value: 'Automatic' },
    ],
    features: [
      'Powerful vacuum pressure airtight sealing',
      'Hygienic stainless steel body',
      'Automatic operation',
      'Simple user-friendly control panel',
      'Extends freshness significantly',
      'Works with wet, dry, oil, powder foods',
    ],
    applications: [
      'Fresh meat & fish',
      'Cooked food',
      'Liquid sauces',
      'Fresh fruit',
      'Grains',
      'Commercial packaging',
    ],
    warranty: '1-Year Warranty',
  },
  {
    slug: 'dz500-2r',
    category: 'vacuum-sealers',
    nameEn: 'DZ500-2R Vacuum Sealer',
    nameSi: 'DZ500-2R රික්ත සීල්',
    price: 895000,
    descEn: 'Round-chamber vacuum sealer 500mm.',
    descSi: 'DZ500-2R රික්ත සීල් යන්ත්‍රය.',
    image: '/images/products/dz500-2r.png',
    highlights: [
      { icon: '🌀', label: 'Type', value: 'Round Chamber' },
      { icon: '🛡', label: 'Body', value: 'SS Body' },
      { icon: '📦', label: 'Size', value: 'Large 500mm' },
    ],
    features: [
      'Larger 500mm round chamber',
      'Powerful vacuum pressure airtight sealing',
      'Automatic operation',
      'Extends product freshness significantly',
    ],
    applications: ['Fresh meat & fish', 'Commercial food packaging', 'Large batches'],
    warranty: '1-Year Warranty',
  },
  {
    slug: 'dz500-2d',
    category: 'vacuum-sealers',
    nameEn: 'DZ500-2D Vacuum Sealer',
    nameSi: 'DZ500-2D රික්ත සීල්',
    price: null,
    descEn: 'Double-chamber vacuum sealer.',
    descSi: 'DZ500-2D රික්ත සීල් යන්ත්‍රය.',
    image: '/images/products/dz500-2d.png',
    highlights: [
      { icon: '🌀', label: 'Type', value: 'Double Chamber' },
      { icon: '🛡', label: 'Body', value: 'SS Body' },
      { icon: '📦', label: 'Size', value: 'Large Capacity' },
    ],
    features: [
      'Larger chamber than DZ400 for bigger batches',
      'Powerful vacuum pressure airtight sealing',
      'Hygienic stainless steel body',
      'Automatic operation',
      'Extends product freshness significantly',
    ],
    applications: [
      'Fresh meat & fish',
      'Commercial food packaging',
      'Liquid products',
      'Grains & dry goods',
    ],
    warranty: '1-Year Warranty',
  },
  {
    slug: 'sy260t',
    category: 'vacuum-sealers',
    nameEn: 'SY260T Vacuum Sealer',
    nameSi: 'SY260T රික්ත සීල්',
    price: 195000,
    descEn: 'Tabletop vacuum sealer.',
    descSi: 'SY260T රික්ත සීල් යන්ත්‍රය.',
    image: '/images/products/sy260t.png',
    highlights: [
      { icon: '⚡', label: 'Sealer Power', value: '300W' },
      { icon: '💪', label: 'Pump Power', value: '370W' },
      { icon: '📐', label: 'Sealing Width', value: '20 cm' },
    ],
    specs: [
      { label: 'Sealer Power', value: '300W' },
      { label: 'Vacuum Pump Power', value: '370W' },
      { label: 'Machine Weight', value: '38.5 kg' },
      { label: 'Sealing Size', value: '20 cm' },
      { label: 'Dimensions', value: '50 × 34 × 38 cm' },
      { label: 'Vacuum Pressure', value: '<1 kPa' },
      { label: 'Warranty', value: '1 Year' },
    ],
    features: [
      'Compact and powerful design',
      'Stainless steel body construction',
      'Digital control system',
      'Automatic operation for consistent sealing',
      'Works with wet/dry food products',
      'Extends product shelf life significantly',
    ],
    applications: [
      'Fresh meat & fish',
      'Cooked food packaging',
      'Liquid sauces',
      'Fresh fruits',
      'Grains & dry goods',
      'Commercial food packaging',
    ],
    warranty: '1-Year Warranty',
  },
  {
    slug: 'sy500t',
    category: 'vacuum-sealers',
    nameEn: 'SY500T Vacuum Sealer',
    nameSi: 'SY500T රික්ත සීල්',
    price: 455500,
    descEn: 'Large vacuum sealer.',
    descSi: 'SY500T රික්ත සීල් යන්ත්‍රය.',
    image: '/images/products/sy500t.png',
    highlights: [
      { icon: '🌀', label: 'Type', value: 'Large Tabletop' },
      { icon: '🛡', label: 'Body', value: 'SS Body' },
      { icon: '📦', label: 'Capacity', value: 'High Volume' },
    ],
    features: [
      'Large-capacity tabletop vacuum sealer',
      'Professional-grade stainless steel construction',
      'Automatic vacuum and sealing cycle',
      'Suitable for large packaging operations',
    ],
    applications: [
      'Commercial food processing',
      'Meat & fish packaging',
      'Restaurant & catering use',
    ],
    warranty: '1-Year Warranty',
  },
  // ── Rice Mills ──
  {
    slug: 'lokka-rice-mill',
    category: 'rice-mills',
    nameEn: 'Lokka Rice Mill',
    nameSi: 'ලොක්කා සහල් කෝල්',
    price: 1550000,
    descEn: 'Lokka brand rice mill.',
    descSi: 'ලොක්කා සහල් කෝල් යන්ත්‍රය.',
    image: '/images/products/lokka-rice-mill.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '500–600 kg/h' },
      { icon: '💪', label: 'Power', value: '10HP / 7.5kW' },
      { icon: '🌾', label: 'Rice Yield', value: '60–65%' },
    ],
    specs: [
      { label: 'Processing Capacity', value: '500–600 kg/h' },
      { label: 'Power', value: '10HP / 7.5kW' },
      { label: 'Rice Yield', value: '60–65%' },
      { label: 'Floor Space', value: '4 × 3.6 × 5.5 meters' },
      { label: 'Warranty', value: '6 months machine / 12 months labor' },
    ],
    features: [
      'Complete 100% stone removal',
      'Broken rice separation with precision',
      'Double-knob impurity control',
      'Transparent separator for quality monitoring',
      'High technical service capability',
      'Low power consumption for output ratio',
      'Commercial-grade heavy duty construction',
    ],
    applications: [
      'Commercial rice milling',
      'Agricultural grain processing',
      'High-volume rice production',
      'Custom milling services',
    ],
    warranty: '12-Month Labor / 6-Month Machine Warranty',
    includes: [
      '6N 1000 Rice Mill Machine (Main Unit)',
      'Destoner Machine (0.8kW / 1HP)',
      'Separator Unit for quality grading',
      'Full installation support',
    ],
  },
  {
    slug: 'saviya-rice-mill',
    category: 'rice-mills',
    nameEn: 'Saviya Rice Mill',
    nameSi: 'සවිය සහල් කෝල්',
    price: 1399000,
    descEn: 'Saviya brand rice mill.',
    descSi: 'සවිය සහල් කෝල් යන්ත්‍රය.',
    image: '/images/products/saviya-rice-mill.png',
    highlights: [
      { icon: '⚡', label: 'Capacity', value: '250–300 kg/h' },
      { icon: '💪', label: 'Power', value: '10HP / 7.5kW' },
      { icon: '🌾', label: 'Rice Yield', value: '60–65%' },
    ],
    specs: [
      { label: 'Processing Capacity', value: '250–300 kg/h' },
      { label: 'Power', value: '10HP / 7.5kW' },
      { label: 'Rice Yield', value: '60–65%' },
      { label: 'Floor Space', value: '4 × 3.6 × 5.5 meters' },
      { label: 'Warranty', value: '6 months machine / 12 months parts' },
    ],
    features: [
      'Complete 5-in-1 processing system',
      'Destoner removes 100% of stones',
      'Elevator unit for smooth flow',
      'Separator for quality grading',
      'Low power consumption',
      'Compact integrated design',
    ],
    applications: [
      'Small to medium commercial rice milling',
      'Mixed grain processing',
      'Market-ready rice production',
    ],
    warranty: '12-Month Parts / 6-Month Machine Warranty',
    includes: [
      '5-IN-1 Mill Unit (250–300 kg/h)',
      'Destoner Machine (600 kg/h)',
      'Elevator Unit (2.5 × 2.5 × 6 m)',
      'Separator Unit',
      'Full installation support',
    ],
  },
  {
    slug: 'ransahal-rice-mill',
    category: 'rice-mills',
    nameEn: 'Ransahal Rice Mill (BBN2023A21)',
    nameSi: 'රන්සහල් සහල් කෝල්',
    price: 1355000,
    descEn: 'Ransahal rice mill with destoner. 200–250 kg/h, 220V single phase. Removes husk, polishes and sorts rice.',
    descSi: 'රන්සහල් සහල් කෝල් — ගල් ඉවත් කිරීම, දිලිසෙන, වර්ග කිරීම.',
    image: '/images/products/ransahal-rice-mill.png',
    highlights: [
      { icon: '🌾', label: 'Type', value: 'Rice Mill' },
      { icon: '💪', label: 'Brand', value: 'Ransahal' },
      { icon: '✅', label: 'Warranty', value: 'Included' },
    ],
    features: [
      'Commercial-grade rice milling',
      'Complete milling system',
      'Stone removal capability',
      'High rice yield output',
    ],
    applications: [
      'Commercial rice milling',
      'Agricultural processing',
    ],
    warranty: '12-Month Warranty',
  },
  // ── Slicers ──
  {
    slug: 'hd-300-slicer',
    category: 'slicers',
    nameEn: 'HD-300 Slicer',
    nameSi: 'HD-300 පෙති කොටන',
    price: 49500,
    descEn: 'Food slicer machine.',
    descSi: 'HD-300 ආහාර පෙති කොටන යන්ත්‍රය.',
    image: '/images/products/hd-300-slicer.png',
    highlights: [
      { icon: '🔪', label: 'Thickness', value: '0.2–10 mm' },
      { icon: '⚖️', label: 'Weight', value: '4 kg' },
      { icon: '📐', label: 'Food Slot', value: '18 × 11.5 cm' },
    ],
    specs: [
      { label: 'Thickness Range', value: '0.2–10 mm' },
      { label: 'Weight', value: '4 kg' },
      { label: 'Food Slot Size', value: '18 × 11.5 cm' },
      { label: 'Dimensions', value: '26 × 27 × 35 cm' },
      { label: 'Warranty', value: '6 months' },
    ],
    features: [
      'Double knife slicing mechanism',
      'Enlarged inlet for bigger produce',
      'Elastic pull tab for safety',
      'Adjustable thickness 0.2–10mm',
      'Compact lightweight design',
      'Easy to clean',
    ],
    applications: [
      'Fruits slicing (banana, apple, mango)',
      'Vegetable slicing',
      'Bread slicing',
      'Meat slicing',
      'Commercial food prep',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'hd-400-slicer',
    category: 'slicers',
    nameEn: 'HD-400 Slicer',
    nameSi: 'HD-400 පෙති කොටන',
    price: 99500,
    descEn: 'Food slicer machine.',
    descSi: 'HD-400 ආහාර පෙති කොටන යන්ත්‍රය.',
    image: '/images/products/hd-400-slicer.png',
    highlights: [
      { icon: '🔪', label: 'Thickness', value: '0–8 mm' },
      { icon: '🔌', label: 'Power', value: '220V Electric' },
      { icon: '📐', label: 'Food Slot', value: '14–22 cm' },
    ],
    specs: [
      { label: 'Thickness Range', value: '0–8 mm' },
      { label: 'Voltage', value: '220V' },
      { label: 'Weight', value: '10 kg' },
      { label: 'Food Slot', value: '14–22 cm' },
      { label: 'Dimensions', value: '30 × 35 × 45 cm' },
      { label: 'Warranty', value: '6 months' },
    ],
    features: [
      'One-press slicing operation',
      'Large food slot for various produce sizes',
      'Adjustable slice thickness',
      'Thickened safety cover',
      'Electric-powered for consistency',
      'High-volume industrial capable',
    ],
    applications: [
      'Fruits slicing',
      'Vegetable slicing',
      'Commercial food processing',
      'Restaurant use',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'hd-500-slicer',
    category: 'slicers',
    nameEn: 'HD-500 Slicer',
    nameSi: 'HD-500 පෙති කොටන',
    price: 99500,
    descEn: 'Food slicer machine.',
    descSi: 'HD-500 ආහාර පෙති කොටන යන්ත්‍රය.',
    image: '/images/products/hd-500-slicer.jpg',
    highlights: [
      { icon: '🔪', label: 'Thickness', value: '0–13 mm' },
      { icon: '⚡', label: 'Power', value: '40W Electric' },
      { icon: '🔄', label: 'Blade', value: '24.3 cm' },
    ],
    specs: [
      { label: 'Power', value: '40W Electric' },
      { label: 'Cutter Diameter', value: '24.3 cm' },
      { label: 'Thickness Range', value: '0–13 mm' },
      { label: 'Weight', value: '5 kg' },
      { label: 'Food Chute', value: '8.7 × 3.7 × 5.7 cm' },
      { label: 'Dimensions', value: '32 × 27 × 28.5 cm' },
      { label: 'Warranty', value: '6 months' },
    ],
    features: [
      'Electric-powered precision slicing',
      'Large 24.3cm cutting blade',
      'Wide 0–13mm thickness range',
      'Compact and lightweight (5kg)',
      'Consistent uniform slices',
      'Easy cleaning design',
      'Low power consumption 40W',
    ],
    applications: [
      'Fruits & vegetables',
      'Commercial food processing',
      'Meat slicing',
      'Bakery bread slicing',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: '180-model-cutting',
    category: 'slicers',
    nameEn: '180 Model Cutting Machine',
    nameSi: '180 මොඩල් කැපීමේ යන්ත්‍රය',
    price: null,
    descEn: 'Multi-purpose 180 model commercial cutting machine.',
    descSi: '180 මොඩල් කට් යන්ත්‍රය.',
    image: '/images/products/180-model-cutting.jpg',
    highlights: [
      { icon: '🔪', label: 'Type',     value: 'Commercial Cutter' },
      { icon: '🏭', label: 'Scale',    value: 'Commercial' },
      { icon: '🔄', label: 'Model',    value: '180 Model' },
    ],
    features: [
      'Commercial-grade cutting machine',
      'Suitable for various food products',
      'Consistent cutting performance',
      'Easy operation and maintenance',
    ],
    applications: [
      'Commercial food processing',
      'Vegetable and fruit cutting',
      'Restaurant and catering use',
    ],
    warranty: '6-Month Warranty',
  },
  // ── Chuff Cutters ──
  {
    slug: 'bbz-15-chuff',
    category: 'chuff-cutters',
    nameEn: 'BBZ 1.5 Chuff Cutter',
    nameSi: 'BBZ 1.5 කොළ කොටන',
    price: 165500,
    descEn: 'Chuff cutter machine.',
    descSi: 'BBZ 1.5 කොළ කොටන යන්ත්‍රය.',
    image: '/images/products/bbz-15-chuff.png',
    highlights: [
      { icon: '🌿', label: 'Type', value: 'Motor Driven' },
      { icon: '⚡', label: 'Capacity', value: 'High Volume' },
      { icon: '🔄', label: 'Model', value: 'BBZ 1.5' },
    ],
    features: [
      'Motor-driven efficient cutting',
      'Heavy-duty blade construction',
      'Suitable for grass hay and agricultural fodder',
      'Easy operation and maintenance',
      'Durable commercial build',
    ],
    applications: [
      'Animal feed preparation',
      'Grass and hay cutting',
      'Agricultural fodder processing',
      'Farm use',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'km-15-chuff',
    category: 'chuff-cutters',
    nameEn: 'KM 1.5 Chuff Cutter',
    nameSi: 'KM 1.5 කොළ කොටන',
    price: 165000,
    descEn: 'KM 1.5 chuff cutter with engine option.',
    descSi: 'KM 1.5 කොළ කොටන යන්ත්‍රය.',
    image: '/images/products/km-15-chuff.png',
    highlights: [
      { icon: '🌿', label: 'Type',     value: 'Engine Driven' },
      { icon: '⚡', label: 'Capacity', value: 'High Volume' },
      { icon: '🔄', label: 'Model',    value: 'KM 1.5' },
    ],
    features: [
      'Engine-driven for high-power cutting',
      'Heavy-duty blade construction',
      'Suitable for wet and dry fodder',
      'Durable agricultural build',
    ],
    applications: [
      'Animal feed preparation',
      'Grass and hay cutting',
      'Agricultural fodder',
      'Farm and livestock use',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: '9z-15-chuff',
    category: 'chuff-cutters',
    nameEn: '9Z 1.5 Chuff Cutter',
    nameSi: '9Z 1.5 කොළ කොටන',
    price: 189500,
    descEn: 'Chuff cutter machine.',
    descSi: '9Z 1.5 කොළ කොටන යන්ත්‍රය.',
    image: '/images/products/9z-15-chuff.png',
    highlights: [
      { icon: '🌿', label: 'Type', value: 'Engine/Motor' },
      { icon: '⚡', label: 'Capacity', value: 'High Volume' },
      { icon: '🔄', label: 'Model', value: '9Z 1.5' },
    ],
    features: [
      'Available with motor or engine options',
      'Heavy-duty chuff cutting',
      'Suitable for wet and dry fodder',
      'Robust agricultural build',
    ],
    applications: [
      'Animal feed preparation',
      'Grass cutting',
      'Agricultural fodder',
      'Farm and livestock use',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: 'bb-cvt-chuff',
    category: 'chuff-cutters',
    nameEn: 'BB-CVT Chuff Cutter',
    nameSi: 'BB-CVT කොළ කොටන',
    price: 485000,
    descEn: 'Chuff cutter machine.',
    descSi: 'BB-CVT කොළ කොටන යන්ත්‍රය.',
    image: '/images/products/bb-cvt-chuff.png',
    highlights: [
      { icon: '🌿', label: 'Transmission', value: 'CVT' },
      { icon: '⚡', label: 'Control', value: 'Variable Speed' },
      { icon: '🔄', label: 'Model', value: 'BB-CVT' },
    ],
    features: [
      'Continuously variable transmission (CVT)',
      'Adjustable cutting speed',
      'Smooth operation control',
      'Heavy-duty construction',
      'Fuel efficient design',
    ],
    applications: [
      'Agricultural fodder cutting',
      'Animal feed preparation',
      'Farm machinery',
    ],
    warranty: '6-Month Warranty',
  },
  {
    slug: '9zt-60-chuff',
    category: 'chuff-cutters',
    nameEn: '9ZT-6.0 Chuff Cutter',
    nameSi: '9ZT-6.0 කොළ කොටන',
    price: 245000,
    descEn: 'Chuff cutter machine.',
    descSi: '9ZT-6.0 කොළ කොටන යන්ත්‍රය.',
    image: '/images/products/9zt-60-chuff.png',
    highlights: [
      { icon: '🌿', label: 'Capacity', value: 'High Output' },
      { icon: '💪', label: 'Power', value: '6.0 kW' },
      { icon: '🔄', label: 'Model', value: '9ZT-6.0' },
    ],
    features: [
      'High-capacity 6.0kW powerful cutting',
      'Heavy-duty commercial grade',
      'Large volume fodder processing',
      'Robust reliable construction',
    ],
    applications: [
      'Large farm fodder processing',
      'Commercial agricultural use',
      'High-volume animal feed preparation',
    ],
    warranty: '6-Month Warranty',
  },
  // ── Wood Chippers ──
  {
    slug: '9zq-6q-wood-chipper',
    category: 'wood-chippers',
    nameEn: '9ZQ-6Q Wood Chipper',
    nameSi: '9ZQ-6Q ලී කොටන යන්ත්‍රය',
    price: 195000,
    descEn: 'High-efficiency wood chipper.',
    descSi: '9ZQ-6Q ලී කොටන යන්ත්‍රය.',
    image: '/images/products/9zq-6q-wood-chipper.png',
    highlights: [
      { icon: '💪', label: 'Capacity', value: '≥700 kg/h' },
      { icon: '🔥', label: 'Power', value: '7.5 HP' },
      { icon: '🔄', label: 'RPM', value: '1800–2200' },
    ],
    specs: [
      { label: 'Capacity', value: '≥700 kg/h' },
      { label: 'Power', value: '7.5 HP' },
      { label: 'RPM', value: '1800–2200' },
      { label: 'Weight', value: '62 kg' },
      { label: 'Dimensions', value: '125 × 16 × 98.7 cm' },
      { label: 'Industry', value: 'Agriculture & Farming' },
      { label: 'Warranty', value: '1 Year' },
    ],
    features: [
      'High efficiency and energy saving design',
      'Safety protection devices for operators',
      'Processes waste branches into quality chips',
      'Reduces rural household waste & pollution',
      'Heavy-duty gasoline engine operation',
    ],
    applications: [
      'Agricultural mulching',
      'Biomass fuel generation',
      'Building materials',
      'Fertilizer and flower cultivation mulch',
      'Waste resource utilization',
    ],
    warranty: '1-Year Machine Warranty',
  },
  {
    slug: '9zq-12q-wood-chipper',
    category: 'wood-chippers',
    nameEn: '9ZQ-12Q Wood Chipper',
    nameSi: '9ZQ-12Q ලී කොටන යන්ත්‍රය',
    price: 495000,
    descEn: 'High-capacity wood chipper.',
    descSi: '9ZQ-12Q ලී කොටන යන්ත්‍රය.',
    image: '/images/products/9zq-12q-wood-chipper.png',
    highlights: [
      { icon: '💪', label: 'Capacity', value: '≥1400 kg/h' },
      { icon: '🔥', label: 'Power', value: '16 HP' },
      { icon: '🔄', label: 'RPM', value: '1200–1500' },
    ],
    specs: [
      { label: 'Capacity', value: '≥1400 kg/h' },
      { label: 'Power', value: '16 HP' },
      { label: 'RPM', value: '1200–1500' },
      { label: 'Weight', value: '100 kg' },
      { label: 'Dimensions', value: '125 × 46 × 123 cm' },
      { label: 'Industry', value: 'Agriculture & Farming' },
      { label: 'Warranty', value: '1 Year' },
    ],
    features: [
      'High-power 16HP engine for heavy loads',
      'Double the capacity of smaller models',
      'Safety protection mechanisms',
      'High efficiency energy-saving operation',
      'Commercial-grade heavy duty construction',
    ],
    applications: [
      'Large-scale agricultural mulching',
      'Commercial biomass fuel production',
      'Industrial wood waste processing',
      'Large plantation maintenance',
    ],
    warranty: '1-Year Machine Warranty',
  },
  // ── Feed Pellet ──
  {
    slug: 'feed-pellet-180',
    category: 'feed-pellet',
    nameEn: 'Feed Pellet Machine 180',
    nameSi: 'ගොරෝසු ඇට යන්ත්‍රය 180',
    price: 297500,
    descEn: 'Feed pellet machine up to 200 kg/h.',
    descSi: 'ගොරෝසු ඇට යන්ත්‍රය 180.',
    image: '/images/products/feed-pellet-180.png',
    highlights: [
      { icon: '🐄', label: 'Capacity', value: 'Up to 200 kg/h' },
      { icon: '🔘', label: 'Pellet Sizes', value: '2 / 4 / 6 mm' },
      { icon: '🔄', label: 'System', value: '4-Roller' },
    ],
    specs: [
      { label: 'Production Capacity', value: 'Up to 200 kg/h' },
      { label: 'Pellet Sizes', value: '2mm / 4mm / 6mm' },
      { label: 'Roller System', value: '4-Roller' },
      { label: 'Motor', value: '100% Copper-plated Electric' },
      { label: 'Transmission', value: 'Low-noise auto-leveling coupling' },
    ],
    features: [
      '4-roller system for consistent pellet formation',
      '100% copper-plated durable electric motor',
      'Well-finished discharge outlet for smooth flow',
      'Low-noise transmission with auto-leveling',
      'Converts agro-waste into premium animal feed',
      'Cost-effective — 60% below market price',
      'Multipurpose — handles various feed types',
    ],
    applications: [
      'Poultry feed production',
      'Livestock feed pellets',
      'Fish feed manufacturing',
      'Converting agricultural waste to feed',
    ],
    warranty: '12-Month Warranty',
    includes: [
      'Feed Pellet Machine 180',
      'User Manual',
      'Spare Die Set',
    ],
  },
  {
    slug: 'feed-pellet-210',
    category: 'feed-pellet',
    nameEn: 'Feed Pellet Machine 210',
    nameSi: 'ගොරෝසු ඇට යන්ත්‍රය 210',
    price: 525000,
    descEn: 'Feed pellet machine up to 300 kg/h.',
    descSi: 'ගොරෝසු ඇට යන්ත්‍රය 210.',
    image: '/images/products/feed-pellet-210.png',
    highlights: [
      { icon: '🐄', label: 'Capacity', value: 'Up to 300 kg/h' },
      { icon: '🔘', label: 'Pellet Sizes', value: '2 / 4 / 6 mm' },
      { icon: '🔄', label: 'System', value: '2-Roller' },
    ],
    specs: [
      { label: 'Production Capacity', value: 'Up to 300 kg/h' },
      { label: 'Pellet Sizes', value: '2mm / 4mm / 6mm' },
      { label: 'Roller System', value: '2 Grooved Rollers' },
      { label: 'Motor', value: '100% Copper-plated Electric' },
      { label: 'Transmission', value: 'Efficient coupling with auto-leveling' },
    ],
    features: [
      'Higher 300 kg/h production capacity',
      '2 grooved rollers for efficient compression',
      '100% copper-plated durable motor',
      'Smooth discharge outlet',
      'Versatile — handles multiple feed types',
      'Commercial-grade construction',
    ],
    applications: [
      'Commercial poultry feed production',
      'Large-scale livestock feed',
      'Fish & aquaculture feed',
      'Agricultural waste conversion',
    ],
    warranty: '12-Month Warranty',
  },
]

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter(p => p.category === category)
}

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug)
}

export function formatPrice(price: number | null): string {
  if (price === null) return 'Contact for Price'
  return `LKR ${price.toLocaleString('en-LK')}`
}
